name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: 3.9
          poetry-version: 1.7.1

      - name: List Dependencies
        uses: divideprojects/poetry-export-requirements-action@v1.4.0

      - name: List Directory Structure
        run: |
          Get-ChildItem -Path . -Recurse
        shell: powershell

      - name: Build Executable
        uses: sayyid5416/pyinstaller@v1.2.0
        with:
          python_ver: '3.9'
          spec: 'ScrapeyDoo.spec'
          requirements: 'requirements.txt'

      - name: Test Executable
        run: |
          .\dist\ScrapeyDoo.exe
        shell: powershell

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "dist/*"