name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: 3.9
          poetry-version: 1.7.1

      - name: Build Executable
        run: |
          poetry run python build.py

      - name: Test Executable
        run: |
          $query = Get-Content .\tests\query.json -Raw | ConvertFrom-Json | ConvertTo-Json -Compress
          .\dist\ScrapeyDoo.exe
          .\dist\ScrapeyDoo.exe "$query"
        shell: powershell

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "dist/*"