name: Build

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: "3.9"
          poetry-version: "1.8.3"

      - name: Build Executable
        run: >
          poetry run pyinstaller
          --onefile
          --windowed
          --argv-emulation
          --name ScrapeyDoo
          --icon src/assets/ScrapeyDoo.ico
          --add-data src/assets:assets
          --paths src
          --additional-hooks-dir src/hooks
          --hidden-import settings
          --add-data src/resources:resources
          --noconfirm
          src/__init__.py

      - name: Test Executable
        run: |
          ./dist/ScrapeyDoo.exe &
          sleep 10
          if [ -f ./dist/CRASH.dump ]; then
            cat ./dist/CRASH.dump
            exit 1
          fi

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "dist/*"
